### PR TITLE
Reject now takes alias instead of the default command word.

### LINKED ISSUE #163: [PE-D][Tester D] Alias for "reject" does not work as intended
When an alias for the "reject" command is created, the alias does not work. 

Image

Steps taken:
1. add a new internship entry
2. set a new alias for the "reject" command (alias is "rej")
3. tested the reject command using the alias, according to the original reject command format and a valid index (i.e rej INDEX)
4. tested the original reject command (reject INDEX) 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by the-RoaringCat**
close #163

### CODE REVIEW

File: src/main/java/seedu/goldencompass/command/RejectOfferCommand.java [hunk 1]
```diff
@@ -44,18 +43,17 @@ public void execute() throws GoldenCompassException {
         logger.log(Level.INFO, "Starting execution of RejectCommand...");
 
         // Assuming your team's command word is "reject"
-        List<String> params = parser.getParamsOf("reject");
-
+        String param = parser.getDefaultParam();
         // 1. DEFENSIVE CHECK: Missing index
```
Comment (liny666) [inline src/main/java/seedu/goldencompass/command/RejectOfferCommand.java:47]: `getDefaultParam()` is implemented as `getParamsOf(command).get(0)` with no null/empty guard — if `getParamsOf` returns null or an empty list, this throws an uncaught `NullPointerException` or `IndexOutOfBoundsException` before the null check on line 49 even runs. The safer pattern used by most other commands is:
```java
List<String> params = parser.getParamsOf(parser.getCommand());
if (params == null || params.isEmpty() || params.get(0).isBlank()) { ... }
String param = params.get(0).trim();
```

File: src/main/java/seedu/goldencompass/command/RejectOfferCommand.java [hunk 2]
```diff
@@ -44,18 +43,17 @@ public void execute() throws GoldenCompassException {
         logger.log(Level.INFO, "Starting execution of RejectCommand...");
 
         // Assuming your team's command word is "reject"
-        List<String> params = parser.getParamsOf("reject");
-
+        String param = parser.getDefaultParam();
```
Comment (liny666) [inline src/main/java/seedu/goldencompass/command/RejectOfferCommand.java:46]: This comment — "Assuming your team's command word is 'reject'" — was a placeholder from when the string was hardcoded. Now that the hardcoded string is removed, it's stale and misleading. Please delete it.

**Review by liny666 — COMMENTED** [review]
No test for the alias path — the stated goal is that `reject` works when invoked via an alias, but there's no test that registers an alias and verifies the command executes correctly through it. Without it, this regression could silently reappear.
