### PR TITLE
fixed issues in 'add' command

### LINKED ISSUE #170: [PE-D][Tester A] Extremely long company name or title is accepted without restriction or warning
Steps to reproduce:
1. add AAAA...(10000 chars)... /t Engineer

Expected: Input rejected or warned as unreasonably long, or display truncated gracefully.

Actual: Input accepted silently. Display wraps unreadably across terminal.
This violates the UG's own note that terminal width of at least 80 characters is recommended.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`

### LINKED ISSUE #173: [PE-D][Tester A] Identical internship entries can be added multiple times with no duplicate warning
Steps to reproduce:
1. add Grab /t Software Engineer
2. add Grab /t Software Engineer
3. list

Expected: Warning or rejection when an identical company + role entry already exists.

Actual: Both entries added successfully. list shows two identical entries:
1. Grab - Software Engineer
2. Grab - Software Engineer

-------------
Labels: `severity.Medium` `type.FeatureFlaw`

### LINKED ISSUE #183: [PE-D][Tester B] Application allows adding internships with whitespace only company and title
### Description
The application accepts inputs where both the company name and internship title consist only of whitespace. This leads to meaningless entries being added to the internship list.

### Steps to Reproduce
1. Run the application  
2. Enter:
   add "   " /t "   "  
3. Run:
   list  

### Expected
The application should reject inputs where the company name or title is empty or contains only whitespace, and display an appropriate error message.

### Actual
The application accepts the input and adds an internship:
" " - " "

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #184: [PE-D][Tester B] Duplicate internships can be added without restriction
### Description
The application allows identical internships (same company and title) to be added multiple times, which may lead to redundant data.

### Steps to Reproduce
add Grab /t SE  
add Grab /t SE  
list  

### Expected
The application should either:
- Prevent duplicate entries, or
- Warn the user about duplicates

### Actual
Multiple identical entries are added to the list.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`

### LINKED ISSUE #189: [PE-D][Tester B] Application treats duplicates differently from search (case inconsistency)
### Description
The application treats internships with different letter casing as distinct entries when adding, but treats them as the same during search. This leads to inconsistent behavior.

### Steps to Reproduce
add Grab /t SE  
add grab /t se  
search /c GRAB  

### Expected
The system should handle case consistently across features (either fully case-sensitive or case-insensitive).

### Actual
Duplicate entries are allowed, but search treats them as the same.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #191: [PE-D][Tester B] Enhance validation for company and internship title inputs
### Description
The application currently allows inputs with only special characters, excessive whitespace, or very short names (e.g., single-character company names), which may reduce data quality.

### Suggestion
- Enforce minimum length (e.g., at least 2 characters)
- Reject inputs containing only whitespace
- Limit excessive special characters

-------------
Labels: `severity.Low` `type.DocumentationBug`

### LINKED ISSUE #201: [PE-D][Tester E] Internship with “ | ” in company name is permanently lost after restart
If a company name contains “ |  " (different from "|"), the internship is permanently lost after restart with no warning to the user.

Steps to reproduce:
add Google | Meta /t SWE
list — verify the internship appears as entry 7: Google | Meta - SWE
bye
Restart: java -jar goldencompass.jar
list

Expected: Google | Meta - SWE is still present in the list after restart.
Actual: The internship is gone. No error or warning is shown during saving or loading.
Screenshot evidence:
Image

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by xiranhu**
fixes #201 fixes #191 fixes #184 fixes #183 fixes #173 fixes #170 fixes #189

### CODE REVIEW

File: src/main/java/seedu/goldencompass/command/AddInternshipCommand.java [hunk 1]
```diff
@@ -82,7 +82,30 @@ public void execute() throws GoldenCompassException {
...
+            errorMessage.append("Only alphanumeric characters and commas ',' are permitted.\n");
+        }
+
+        if (!errorMessage.isEmpty()) {
+            throw new GoldenCompassException(errorMessage.toString().trim());
+        }
+
         Internship newInternship = new Internship(title, companyName);
+
+        for (int i = 0; i < internshipList.getSize(); i++) {
```
Comment (the-RoaringCat) [inline src/main/java/seedu/goldencompass/command/AddInternshipCommand.java]: This may be better carried out in `InternshipList#add()`. Reason: there may be other functionalities that add an internship to the list.

Comment (xiranhu) [reply src/main/java/seedu/goldencompass/command/AddInternshipCommand.java]: solved
