### PR TITLE
fixed interview storage error

### LINKED ISSUE #165: [PE-D][Tester D] Incorrect imports upon exiting and restarting program
After the program is exited and restarted, the details of the interview are not imported correctly. In the example below, the name of the titles are imported incorrectly and 1 internship will have 2 interviews. 

Example: 

Image

Steps taken: 
1. added 3 valid internship and interview
2. list interviews
3. sent a delete-interview command for the 3rd interview
4. list interviews which shows that the 1st interview was deleted instead
5. exit the program
6. restart the program
7. list interviews which shows that the same internship has 2 interviews and the current list of interview is different from the list of interviews before exiting the program 

(i think most of the issues i raised were due to internships with repeated company names!)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #182: [PE-D][Tester A] Interviews are misattributed on app reload when two internships share the same company name
Steps to reproduce:
1. add Grab /t Software Engineer
2. add Grab /t Data Analyst
3. add-interview 1 /d 2026-12-01 10:00
4. add-interview 2 /d 2026-12-05 14:00
5. list-interview
   → 1. Grab - Software Engineer @ 2026-12-01 10:00
   → 2. Grab - Data Analyst @ 2026-12-05 14:00
6. Exit and restart the app
7. list-interview
   → 1. Grab - Software Engineer @ 2026-12-01 10:00
   → 2. Grab - Software Engineer @ 2026-12-05 14:00   ← WRONG

The Data Analyst interview is now attributed to Software Engineer.
Root cause: interviews.txt only stores company name (not role), so when
two Grab internships exist, reload can't correctly assign interviews to roles.

After reload, deleting internship 1 (Grab - Software Engineer) also
deletes BOTH interviews, leaving Grab - Data Analyst with no interview.

-------------
Labels: `severity.High` `type.FunctionalityBug`

### LINKED ISSUE #202: [PE-D][Tester E] Two internships from the same company share interviews after restart, causing wrong interview-internship mapping
When two internships from the same company both have interviews, restarting the app causes both interviews to be linked to the first internship of that company. 

Steps to reproduce:
add NUS /t SWE
add NUS /t PM
add-interview 7 /d 2026-04-18 10:00 (index for NUS SWE)
add-interview 8 /d 2026-04-18 10:00 (index for NUS PM)
bye
Restart: java -jar goldencompass.jar
list-interview

Expected:
NUS - SWE @ 2026-04-18 10:00
NUS - PM @ 2026-04-18 10:00
Actual:
NUS - SWE @ 2026-04-18 10:00
NUS - SWE @ 2026-04-18 10:00
Both interviews are mapped to NUS - SWE. The NUS - PM interview data is lost.
Image

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #221: InterviewStorage Null issue
Currently, a string `'null'` is considered legal in the `interviews.txt`.

However, since the user has no way to input a `null` date to an interview, any date field in the `interviews.txt` that cannot be parsed should be regarded as corruption in data, and the corresponding line shall be skipped and display the error.

### PR DESCRIPTION
**Pull request by xiranhu**
fixes #202 fixes #182 fixes #165 
fixes #221

### CODE REVIEW

File: src/main/java/seedu/goldencompass/storage/InterviewStorage.java [hunk 1]
```diff
@@ -59,15 +60,16 @@ public void load(InterviewList interviewList, InternshipList internshipList) {
             while (s.hasNext()) {
                 String line = s.nextLine();
                 String[] parts = line.split(" \\| ");
```
Comment (liny666) [inline src/main/java/seedu/goldencompass/storage/InterviewStorage.java:65]: Breaking change: any existing `interviews.txt` in the old `company | date` format will silently have all entries dropped on the first restart (the `parts.length < 3` check skips them). Users upgrading lose all their saved interviews with no warning. Consider detecting the 2-part format and migrating it, or at minimum printing a warning message.

File: src/main/java/seedu/goldencompass/internship/InternshipList.java [hunk 2]
```diff
@@ -146,4 +146,18 @@ public Internship findInternshipByCompany(String companyName) {
...
+
+    /**
+     * Finds an internship by both company name and role title.
+     * Required for accurately linking interviews upon app restart.
+     */
+    public Internship findInternshipByCompanyAndRole(String companyName, String title) {
+        for (Internship internship : internships) {
+            if (internship.getCompanyName().equalsIgnoreCase(companyName) &&
+                    internship.getTitle().equalsIgnoreCase(title)) {
+                return internship;
```
Comment (liny666) [inline src/main/java/seedu/goldencompass/internship/InternshipList.java:158]: This still returns the first match if two internships share the same company name and role title (e.g. two `Google / SWE` entries). Worth a comment noting this limitation, since the lookup is not guaranteed to be unique.

**Review by liny666 — COMMENTED** [review]
Issue #199 (null date crash on startup) is not fixed by this PR. The `"null"` string is now read back as `dateStr` but the load method never handles the `"null"` string case — it will pass it directly to `LocalDateTime.parse()` and crash. This was flagged as `severity.High` and was listed in the issues this PR references.

File: src/main/java/seedu/goldencompass/storage/InterviewStorage.java [hunk 3]
```diff
@@ -59,15 +60,16 @@ public void load(InterviewList interviewList, InternshipList internshipList) {
...
                 }
 
                 String companyName = parts[0];
-                String dateStr = parts[1];
+                String role = parts[1];
+                String dateStr = parts[2];
 
-                // Find the parent internship by name
-                Internship linkedInternship = internshipList.findInternshipByCompany(companyName);
+                Internship linkedInternship = internshipList.findInternshipByCompanyAndRole(companyName, role);
```
Comment (the-RoaringCat) [inline src/main/java/seedu/goldencompass/storage/InterviewStorage.java:77]: Potential bug: if the data file is corrupted with two interviews with the same `companyName` and `role`, the internship's interview would be overwritten.

File: src/main/java/seedu/goldencompass/storage/InterviewStorage.java [hunk 4]
```diff
@@ -59,15 +60,16 @@ public void load(InterviewList interviewList, InternshipList internshipList) {
...
 
                 if (linkedInternship != null) {
                     Interview interview = new Interview(linkedInternship);
```
Comment (the-RoaringCat) [inline src/main/java/seedu/goldencompass/storage/InterviewStorage.java]: This causes the overwritting.

**Comment by xiranhu** [comment]
> Issue #199 (null date crash on startup) is not fixed by this PR. The `"null"` string is now read back as `dateStr` but the load method never handles the `"null"` string case — it will pass it directly to `LocalDateTime.parse()` and crash. This was flagged as `severity.High` and was listed in the issues this PR references.

isnt this fixed by roaring cat already?

File: src/main/java/seedu/goldencompass/storage/InterviewStorage.java (hunk 3 above)
Comment (the-RoaringCat) [reply src/main/java/seedu/goldencompass/storage/InterviewStorage.java:77]: We are too late to use UUID; thus, rejecting the duplicated interview could be an alternative.

File: src/main/java/seedu/goldencompass/internship/InternshipList.java (hunk 2 above)
Comment (xiranhu) [reply src/main/java/seedu/goldencompass/internship/InternshipList.java:158]: ?we dont even allow duplicate entries now this won't happen.

File: src/main/java/seedu/goldencompass/storage/InterviewStorage.java (hunk 3 above)
Comment (xiranhu) [reply src/main/java/seedu/goldencompass/storage/InterviewStorage.java:77]: the app commands already prevent duplicate internships and interviews from being added, but I added a defensive check in the load() method just to handle manual text-file tampering/corruption

File: src/main/java/seedu/goldencompass/storage/InterviewStorage.java
Comment (uphyrdia) [inline src/main/java/seedu/goldencompass/storage/InterviewStorage.java]: The parsing skips corrupted line silently. I feel there is a need to tell the user which line is corrupted by printing out the original line in txt that is skipped. Further, if the date is corrupted, the interview added will have null dateTime, and any changes will save the null dateTime to txt, overwriting the original corrupted line will date "null". I could imagine two solutions: 2. first try to parse dateStr, and only initialize the interview if it is successful, else the interview object should not be created in the first place. 1. the dateTime of an interview should never be null, and assert it, so no need for the code to handle null case anymore, and treating "null" in txt the same as any other non-LocalDateTime.parsable string.

Comment (uphyrdia) [reply src/main/java/seedu/goldencompass/storage/InterviewStorage.java]: So basically, either 
     create interview object and add to list only if the dateStr is LocalDateTime.parsable (corrupted)
or
     assert dateTime not null in all cases (since add-interview will never introduce null DateTime)

File: src/main/java/seedu/goldencompass/storage/InterviewStorage.java (hunk 1 above)
Comment (xiranhu) [reply src/main/java/seedu/goldencompass/storage/InterviewStorage.java:65]: the users wont have the old version they are gonna use the new version in the correct format

File: src/main/java/seedu/goldencompass/storage/InterviewStorage.java [hunk 5]
```diff
@@ -59,25 +61,47 @@ public void load(InterviewList interviewList, InternshipList internshipList) {
...
+                        parsedDate = LocalDateTime.parse(dateStr);
+                    } catch (DateTimeParseException e) {
+                        new Ui().print("Error: Date is corrupted ('" + dateStr + "') for "
+                                + companyName + " (" + role + "). Skipping.");
+                        continue;
+                    }
+
+                    // Check for duplicates
+                    boolean isDuplicate = false;
+                    for (Interview existing : interviewList.getInterviews()) {
```
Comment (the-RoaringCat) [inline src/main/java/seedu/goldencompass/storage/InterviewStorage.java]: Only need to check if `linkedInternship` has an interview. If it doesn't, its interview should be `null`

**Review by the-RoaringCat — CHANGES_REQUESTED** [review]

File: src/main/java/seedu/goldencompass/storage/InterviewStorage.java [hunk 6]
```diff
@@ -59,25 +61,47 @@ public void load(InterviewList interviewList, InternshipList internshipList) {
...
+                        if (existing.getInternship().equals(linkedInternship)) {
+                            isDuplicate = true;
+                            break;
                         }
                     }
+
+                    if (isDuplicate) {
```
Comment (the-RoaringCat) [inline src/main/java/seedu/goldencompass/storage/InterviewStorage.java]: - This is redundent, if a duplicate is found above, it should immediately process an error message.
- Also, it may be better to use a StringBuilder to process a variable amount of error messages and throw at the end if it is not empty.
