### PR TITLE
Fix

### LINKED ISSUE #162: [PE-D][Tester D] 'bye' command not defined in UG
It's just a small issue but the exit command "bye" was not defined in the User Guide. Maybe you can add it into the Command Summary? Users (like me) might not know how to terminate and exit the program

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`

### LINKED ISSUE #176: [PE-D][Tester D] No error brought up when negative index used for the "upcoming" command
Not a really big issue but perhaps an "invalid index" error can be displayed when the user enters a negative index for the "upcoming" command. Currently the output is that there are no upcoming interviews, but maybe it might be better to let the user know that the index is invalid instead? 

Example: 

Image

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`

### LINKED ISSUE #186: [PE-D][Tester B] upcoming command accepts negative values without validation
### Description
The upcoming command accepts negative numbers as input but does not validate them.

### Steps to Reproduce
upcoming -1  

### Expected
The application should reject negative values and display an error message.

### Actual
You don't have any upcoming interviews.

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### LINKED ISSUE #195: [PE-D][Tester E] Current error message for upcoming + negative index does not match
I feel like it may be better if the error message clearly states the index is not valid
Image

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`

### LINKED ISSUE #196: [PE-D][Tester E] Ambiguous starting point for 5-day window in upcoming command
The User Guide states that if no integer is supplied after upcoming, a default of 5 days will be used. However, during testing, I found that when I key in upcoming, interviews scheduled for 4/10 (today) and 4/15 (six days after today) are both shown. Therefore, I feel the starting point of the 5-day window may be clearly specified.

Steps to reproduce:
add Google /t SWE
Add an interview scheduled for today: add-interview 1 /d <today's date> <future time>
add Meta /t PM
Add an interview 5 days from now: add-interview 2 /d <today+5> 10:00
upcoming
Image

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`

### LINKED ISSUE #200: [PE-D][Tester E] list-interview output includes index numbers not shown in User Guide
The User Guide shows the expected output of list-interview without index numbers. However, the actual output prefixes each entry with a number.

Steps to reproduce:
add Google /t SWE
add-interview 1 /d 2099-06-01 10:00
list-interview
Image
Image

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`

### PR DESCRIPTION
**Pull request by uphyrdia**

### CODE REVIEW

File: src/main/java/seedu/goldencompass/command/UpcomingCommand.java [hunk 1]
```diff
@@ -92,17 +106,18 @@ public void execute() throws GoldenCompassException {
...
 
         assert filteredInterviews.size() <= interviews.size() :
                 "Filtered list cannot be larger than original list";
 
         if (filteredInterviews.isEmpty()) {
-            ui.print("You don't have any upcoming interviews.");
+            ui.print("You don't have any interviews in the upcoming " + days + " day(s).");
         } else {
+            ui.print("You have the following interviews in the upcoming " + days + " day(s):");
             filteredInterviews.forEach(i -> ui.print(i.toString()));
```
Comment (liny666) [inline src/main/java/seedu/goldencompass/command/UpcomingCommand.java:122]: The output message "You have the following interviews in the upcoming -1 day(s):" is confusing — a negative number of upcoming days doesn't read naturally. Consider conditional wording based on the sign of `days`:
- Positive: "You have the following interviews in the upcoming N day(s):"
- Negative: "You have the following interviews in the past N day(s):"

The same applies to the empty-list message and the UG examples.

File: src/main/java/seedu/goldencompass/command/UpcomingCommand.java [hunk 2]
```diff
@@ -72,16 +77,25 @@ public void execute() throws GoldenCompassException {
...
-                throw new GoldenCompassException("The parameter of the upcoming command must be an integer");
+                throw new GoldenCompassException("The parameter of the upcoming command must be a single integer.");
             }
         } else {
             logger.log(Level.INFO, "No parameter provided. Using default days: {0}", DEFAULT_DAYS);
         }
 
         LocalDateTime now = LocalDateTime.now(ZoneId.systemDefault());
-        LocalDateTime limit = now.plusDays(days);
+        LocalDateTime start;
```
Comment (liny666) [inline src/main/java/seedu/goldencompass/command/UpcomingCommand.java:88]: Subtracting 1 minute to account for seconds/microseconds that have already elapsed is a magic-constant workaround. It also leaks into the DG and sequence diagram, adding unnecessary complexity. A cleaner alternative would be to truncate `now` to the minute before computing the interval:
```java
LocalDateTime now = LocalDateTime.now(ZoneId.systemDefault()).truncatedTo(ChronoUnit.MINUTES);
```
This makes the boundary behaviour explicit without a magic offset.

File: src/test/java/seedu/goldencompass/command/UpcomingCommandTest.java [hunk 3]
```diff
@@ -82,21 +83,73 @@ public void execute_upcomingWithIntegerParameter_printsUpcomingInterviewsCorrect
 
     @Test
     public void execute_emptyFilteredList_printsNoUpcomingInterviewsMessage() throws GoldenCompassException {
-        interviewList.add(new Interview(new Internship("Software Engineer", "Google"), now.minusMinutes(1)));
+        interviewList.add(new Interview(new Internship("Software Engineer", "Google"), now.minusMinutes(5)));
```
Comment (liny666) [inline src/test/java/seedu/goldencompass/command/UpcomingCommandTest.java]: The change from `now.minusMinutes(1)` to `now.minusMinutes(5)` here is a direct side-effect of the 1-minute offset workaround — the original value fell within the new window. Also, the newly added `now.plusDays(2)` interview is not asserted anywhere, making it noise in this test case. Consider removing it or adding an explicit assertion.

File: docs/UserGuide.md [hunk 4]
```diff
@@ -380,4 +394,5 @@ same location on the other computer.
 | Undo a command                                | Yes (by`redo`) | `undo`                                              | `undo`                                |
 | Redo a command                                | Yes (by`undo`) | `redo`                                              | `redo`                                |
 | Mark internship application as offer received | Yes            | `mark INDEX`                                        | `mark 4`                              |
-| Mark internship application as rejected       | Yes            | `reject INDEX`                                      | `reject 4`                            |
\ No newline at end of file
+| Mark internship application as rejected       | Yes            | `reject INDEX`                                      | `reject 4`                            |
+| Exit the program                              | No             | `bye`                                               | `bye`                                 |
```
Comment (liny666) [inline docs/UserGuide.md]: The file still ends without a trailing newline (`\ No newline at end of file`). This was already present before this PR, but since a new row is being added to the table, it's a good opportunity to fix it by adding a newline after the last line.

File: src/main/java/seedu/goldencompass/command/UpcomingCommand.java (hunk 1 above)
Comment (uphyrdia) [reply src/main/java/seedu/goldencompass/command/UpcomingCommand.java:122]: This is deliberate since in normal usage one does not use negative number and the command is, after all, called upcoming, and adding another "past" command does not seem to be very useful.

File: src/main/java/seedu/goldencompass/command/UpcomingCommand.java (hunk 2 above)
Comment (uphyrdia) [reply src/main/java/seedu/goldencompass/command/UpcomingCommand.java:88]: Nice suggestion! I have changed the code to use trancatedTo instead in the new commit.

File: src/test/java/seedu/goldencompass/command/UpcomingCommandTest.java (hunk 3 above)
Comment (uphyrdia) [reply src/test/java/seedu/goldencompass/command/UpcomingCommandTest.java]: Yes precisely. The newly added now.plusDays(2) interview is not to be asserted but to ensure future interview beyond the upper bound is not properly filtered out too.

File: docs/UserGuide.md (hunk 4 above)
Comment (uphyrdia) [reply docs/UserGuide.md]: Added.
