### PR TITLE
Reject past dates in update-date for consistency with add-interview

### LINKED ISSUE #166: [PE-D][Tester A] update-date allows past dates unlike add-interview
add Grab /t Software Engineer
add-interview 1 /d 2026-12-01 10:00
update-date 1 /d 2020-01-01 10:00
list-interview

Expected: Error message rejecting the past date, consistent with add-interview behaviour.

Actual: Interview date is silently updated to 2020-01-01 10:00 with no warning.

Screenshots: 

Image

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #180: [PE-D][Tester D] "update-date" command allows for dates in the past
The "update-date" command allows the user to update the interview date to one that is in the past. 

Example: 

Image

Steps Taken: 
1. add a new internship and a valid interview date
2. use the update-date command to update the interview date to an invalid date (in the past) 

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### LINKED ISSUE #185: [PE-D][Tester B] Invalid date is incorrectly reported as "past date"
### Description
When entering an invalid date (e.g. February 30), the application reports it as a past date instead of identifying it as an invalid date.

### Steps to Reproduce
add-interview 1 /d 2025-02-30 10:00  

### Expected
The application should indicate that the date is invalid (e.g. invalid calendar date).

### Actual
Error: Interview date 2025-02-30 10:00 is in the past.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #192: [PE-D][Tester D] "update-date" command updates the wrong interview
After updating an interview with a different date, updating that same index will result in a different interview being updated. 

Image

Steps taken: 
1. add in valid interviews for both existing internships
2.  update the date of interview index 1 with a date later than that of interview index 2
3. display the list of interviews
4. update the date of interview index 1 (according to step 3's display) with a different date
5. display the new updated list of interviews and the wrong interview is updated

in the example, I expected the "McDonalds" interview to be updated after step 4. However at step 5, you can see the "KFC" interview has been updated instead. 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #193: [PE-D][Tester E] Interview date in the past not handled in update-date
For the add-interview function, the date must be in the future. But for the update-interview function, it is not required. Though I am kind of confused, I think it's reasonable to edit the date for interview in the past, I . So no problem if it is deliberately designed in this way can ignore:)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`

### PR DESCRIPTION
**Pull request by liny666**
update-date previously allowed setting an interview deadline to a past date, while add-interview rejected past dates. Flagged in PE-D as inconsistent validation. Apply the same check in
SetInterviewDeadlineCommand and add a regression test.

Fixes #193 
Fixes #180 
Fixes #166 
Fixes #185 
Fixes #192

### CODE REVIEW

File: src/main/java/seedu/goldencompass/command/SetInterviewDeadlineCommand.java [hunk 1]
```diff
@@ -101,25 +102,37 @@ public void execute() throws GoldenCompassException {
...
+                    "Error: " + dateParam + " is not a valid date.");
         }
 
         assert date != null : "Parsed date should not be null";
 
-        List<Interview> sortedInterviews = interviewList.getInterviews().stream()
-                .sorted(Comparator.comparing(Interview::getDate))
-                .toList();
-        Interview interview = sortedInterviews.get(index - 1);
+        if (date.isBefore(LocalDateTime.now())) {
```
Comment (the-RoaringCat) [inline src/main/java/seedu/goldencompass/command/SetInterviewDeadlineCommand.java:122]: Can provide a method in `InterviewList` such as `setDateFor(int index, LocalDateTime dateTime)`, which will validate the date and sort.

Comment (liny666) [reply src/main/java/seedu/goldencompass/command/SetInterviewDeadlineCommand.java:122]: done
